# Generated by Django 3.2.6 on 2021-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
