# Generated by Django 3.2.7 on 2021-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='map_url',
            field=models.URLField(blank=True, help_text='GoogleMap location of the house.'),
        ),
    ]
