# Generated by Django 3.2.7 on 2021-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210905_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('BHK', 'BHK'), ('Paying Guest', 'PG'), ('Single Room', 'Single Room')], max_length=200, null=True),
        ),
    ]
