# Generated by Django 3.2.6 on 2021-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
