# Generated by Django 3.2.6 on 2021-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='is_mvp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
