# Generated by Django 3.2.6 on 2021-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_alter_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
